language: java

jdk:
 - oraclejdk7
 - oraclejdk8
 
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y ant
 - sudo apt-get install -y ecj
 - sudo apt-get install -y dos2unix

 - export PORTLET=${PWD}
 - export INSTALL_ROOT=${HOME}/liferay-portal-6.1.1-ce-ga2
 - env
 - mkdir -p ${INSTALL_ROOT}/deploy
 - mkdir -p ${INSTALL_ROOT}/glassfish-3.1.2/autodeploy
 - mkdir -p ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/applications/liferay-portal/WEB-INF/lib
 - mkdir -p ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/applications/liferay-portal/WEB-INF/tld
 - cd ${HOME}

# Get the Liferay portal with the GlassFish application server (v3.1.2)
 - wget http://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.1.1%20GA2/liferay-portal-glassfish-6.1.1-ce-ga2-20120731132656558.zip/download -O liferay-portal-glassfish-6.1.1-ce-ga2-20120731132656558.zip
 - unzip liferay-portal-glassfish-6.1.1-ce-ga2-20120731132656558.zip

# Get the SDK and unpack it
 - wget http://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.1.1%20GA2/liferay-plugins-sdk-6.1.1-ce-ga2-20121004092655026.zip/download -O liferay-plugins-sdk-6.1.1-ce-ga2-20120731132656558.zip
 - unzip liferay-plugins-sdk-6.1.1-ce-ga2-20120731132656558.zip
 - ls -lht ${INSTALL_ROOT}/*

# Get the build.properties
 - wget http://grid.ct.infn.it/statistics/plugins/build.properties
 - sed -i '/\#javac.compiler=modern/c\javac.compiler=modern' build.properties
 - sed -i '/\javac.compiler=org.eclipse.jdt.core.JDTCompilerAdapter/c\#javac.compiler=org.eclipse.jdt.core.JDTCompilerAdapter' build.properties
 - dos2unix build.properties
 - cp build.properties liferay-plugins-sdk-6.1.1
 - cp -r ${PORTLET} liferay-plugins-sdk-6.1.1/portlets

# Get the ecj.jar
 - wget http://grid.ct.infn.it/statistics/ecj.jar
 - sudo cp ecj.jar /usr/share/ant/lib/

# Copy utils-*.jar to lib/ folder
 - wget http://central.maven.org/maven2/com/liferay/portal/util-taglib/6.1.1/util-taglib-6.1.1.jar
 - wget http://central.maven.org/maven2/com/liferay/portal/util-java/6.1.1/util-java-6.1.1.jar
 - wget http://central.maven.org/maven2/com/liferay/portal/util-bridges/6.1.1/util-bridges-6.1.1.jar
 - cp util-*.jar ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/lib/

# Copy jersey-*.jar to lib/ folder
 - cp ${INSTALL_ROOT}/glassfish-3.1.2/modules/jersey-client.jar ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/lib/
 - cp ${INSTALL_ROOT}/glassfish-3.1.2/modules/jersey-core.jar ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/lib/
 - cp ${INSTALL_ROOT}/glassfish-3.1.2/modules/jersey-json.jar ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/lib/
 - cp ${INSTALL_ROOT}/glassfish-3.1.2/modules/jersey-multipart.jar ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/lib/

# Building the wimea-ict-wrf-portlet
install:
 - cd liferay-plugins-sdk-6.1.1/portlets/wimea-ict-wrf-portlet
 - sudo ant all

notifications:
  email:
    recipients:
        - mario.torrisi@ct.infn.it

